#!/bin/bash

cp arch/arm/mach-msm/msm-buspm-dev.ko compiled/modules/msm-buspm-dev.ko
cp crypto/md4.ko compiled/modules/md4.ko
cp drivers/net/tun.ko compiled/modules/tun.ko
cp drivers/net/wireless/bcmdhd/bcmdhd.ko compiled/modules/bcmdhd.ko
cp drivers/net/wireless/libra/librasdioif.ko compiled/modules/librasdioif.ko
cp drivers/spi/spidev.ko compiled/modules/spidev.ko
cp fs/cifs/cifs.ko compiled/modules/cifs.ko
cp fs/nls/nls_iso8859-1.ko compiled/modules/nls_iso8859-1.ko
cp fs/nls/nls_utf8.ko compiled/modules/nls_utf8.ko
cp fs/ntfs/ntfs.ko compiled/modules/ntfs.ko
cp net/bluetooth/bluetooth.ko compiled/modules/bluetooth.ko
cp net/bluetooth/hidp/hidp.ko compiled/modules/hidp.ko
cp net/wireless/cfg80211.ko compiled/modules/cfg80211.ko
cp net/wireless/lib80211.ko compiled/modules/lib80211.ko


cp arch/arm/boot/zImage compiled/zImage
